### ISSUE TITLE
有个问题想请教

### ISSUE THREAD

**Issue by Tracy028** [cnzero/sEMG_SDK#1]
我用的也是Delsys公司的肌电测量设备，试了一下您的代码，有两个问题：1.在发送START命令时，命令终止符需要设置<CR><LF>，否则无法开启读取数据流的任务。我看您这边没有设置猜想可能和设备有关。2.我能读到数据之后，发现所有的信号值均为0，查找了多方面的原因仍没有头绪，不知您是否遇到过此问题，请指教。我猜想是不是会因为数据流一旦打开，16个通道的数据都会缓存在matlab中，pair的通道是1个或者两个，其余通道的值本来就为0，会不会是在选取对应通道时没匹配起来选成别的通道了

**Comment by cnzero** [comment]
你应该先看下sdk（delays emgworks安装后有个文件夹，里面有各种语言的代码），先有个程序思路；可以自己考虑精简代码，或者看下我在MVC文件夹下面的model代码。欢迎提意见，并贡献代码。

**Comment by Tracy028** [comment]
好的已解决，谢谢。找到了示例代码，主要是设备类型的不同，我改换了另外两端口号，可以正常接收
